//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaveSexton.XmlGel.Maml.Documents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaveSexton.XmlGel.Maml.Documents.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerConceptualDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerConceptualDocument&gt;.
        /// </summary>
        internal static string Conceptual {
            get {
                return ResourceManager.GetString("Conceptual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerErrorMessageDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerErrorMessageDocument&gt;.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerGlossaryDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerGlossaryDocument&gt;.
        /// </summary>
        internal static string Glossary {
            get {
                return ResourceManager.GetString("Glossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerHowToDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerHowToDocument&gt;.
        /// </summary>
        internal static string HowTo {
            get {
                return ResourceManager.GetString("HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerOrientationDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerOrientationDocument&gt;.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;codeEntityDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/codeEntityDocument&gt;.
        /// </summary>
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerReferenceWithoutSyntaxDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerReferenceWithoutSyntaxDocument&gt;.
        /// </summary>
        internal static string ReferenceWithoutSyntax {
            get {
                return ResourceManager.GetString("ReferenceWithoutSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerReferenceWithSyntaxDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerReferenceWithSyntaxDocument&gt;.
        /// </summary>
        internal static string ReferenceWithSyntax {
            get {
                return ResourceManager.GetString("ReferenceWithSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerSampleDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerSampleDocument&gt;.
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerSDKTechnologyOverviewArchitectureDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerSDKTechnologyOverviewArchitectureDocument&gt;.
        /// </summary>
        internal static string SdkArchitecture {
            get {
                return ResourceManager.GetString("SdkArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerSDKTechnologyOverviewCodeDirectoryDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerSDKTechnologyOverviewCodeDirectoryDocument&gt;.
        /// </summary>
        internal static string SdkCodeDirectory {
            get {
                return ResourceManager.GetString("SdkCodeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerSDKTechnologyOverviewOrientationDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerSDKTechnologyOverviewOrientationDocument&gt;.
        /// </summary>
        internal static string SdkOrientation {
            get {
                return ResourceManager.GetString("SdkOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerSDKTechnologyOverviewScenariosDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerSDKTechnologyOverviewScenariosDocument&gt;.
        /// </summary>
        internal static string SdkScenarios {
            get {
                return ResourceManager.GetString("SdkScenarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerSDKTechnologyOverviewTechnologySummaryDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerSDKTechnologyOverviewTechnologySummaryDocument&gt;.
        /// </summary>
        internal static string SdkSummary {
            get {
                return ResourceManager.GetString("SdkSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerTroubleshootingDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerTroubleshootingDocument&gt;.
        /// </summary>
        internal static string Troubleshooting {
            get {
                return ResourceManager.GetString("Troubleshooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerUIReferenceDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerUIReferenceDocument&gt;.
        /// </summary>
        internal static string UserInterface {
            get {
                return ResourceManager.GetString("UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerWalkthroughDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerWalkthroughDocument&gt;.
        /// </summary>
        internal static string Walkthrough {
            get {
                return ResourceManager.GetString("Walkthrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerWhitePaperDocument xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerWhitePaperDocument&gt;.
        /// </summary>
        internal static string Whitepaper {
            get {
                return ResourceManager.GetString("Whitepaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;developerXmlReference xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot; xmlns=&quot;http://ddue.schemas.microsoft.com/authoring/2003/5&quot;&gt;
        ///&lt;/developerXmlReference&gt;.
        /// </summary>
        internal static string XmlReference {
            get {
                return ResourceManager.GetString("XmlReference", resourceCulture);
            }
        }
    }
}
