//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaveSexton.XmlGel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaveSexton.XmlGel.Properties.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        internal static string autoOutline {
            get {
                return ResourceManager.GetString("autoOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This topic contains the following sections..
        /// </summary>
        internal static string AutoOutlineDefaultLead {
            get {
                return ResourceManager.GetString("AutoOutlineDefaultLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a sub-section:.
        /// </summary>
        internal static string AutoOutlineSubsectionDefaultLead {
            get {
                return ResourceManager.GetString("AutoOutlineSubsectionDefaultLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string caption {
            get {
                return ResourceManager.GetString("caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Entity.
        /// </summary>
        internal static string codeEntityReference {
            get {
                return ResourceManager.GetString("codeEntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Reference.
        /// </summary>
        internal static string codeReference {
            get {
                return ResourceManager.GetString("codeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string command {
            get {
                return ResourceManager.GetString("command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Output.
        /// </summary>
        internal static string computerOutput {
            get {
                return ResourceManager.GetString("computerOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation.
        /// </summary>
        internal static string corporation {
            get {
                return ResourceManager.GetString("corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string database {
            get {
                return ResourceManager.GetString("database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions.
        /// </summary>
        internal static string definitionTable {
            get {
                return ResourceManager.GetString("definitionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Variable.
        /// </summary>
        internal static string environmentVariable {
            get {
                return ResourceManager.GetString("environmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Link.
        /// </summary>
        internal static string externalLink {
            get {
                return ResourceManager.GetString("externalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Phrase.
        /// </summary>
        internal static string foreignPhrase {
            get {
                return ResourceManager.GetString("foreignPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string introduction {
            get {
                return ResourceManager.GetString("introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Keyword.
        /// </summary>
        internal static string languageKeyword {
            get {
                return ResourceManager.GetString("languageKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Link.
        /// </summary>
        internal static string legacyLink {
            get {
                return ResourceManager.GetString("legacyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAML Link.
        /// </summary>
        internal static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Literal.
        /// </summary>
        internal static string literal {
            get {
                return ResourceManager.GetString("literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizable User Input.
        /// </summary>
        internal static string localizableUserInput {
            get {
                return ResourceManager.GetString("localizableUserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localized text.
        /// </summary>
        internal static string localizedText {
            get {
                return ResourceManager.GetString("localizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Math.
        /// </summary>
        internal static string math {
            get {
                return ResourceManager.GetString("math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string mediaLink {
            get {
                return ResourceManager.GetString("mediaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Term.
        /// </summary>
        internal static string newTerm {
            get {
                return ResourceManager.GetString("newTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string para {
            get {
                return ResourceManager.GetString("para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string parameter {
            get {
                return ResourceManager.GetString("parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase.
        /// </summary>
        internal static string phrase {
            get {
                return ResourceManager.GetString("phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placeholder.
        /// </summary>
        internal static string placeholder {
            get {
                return ResourceManager.GetString("placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure.
        /// </summary>
        internal static string procedure {
            get {
                return ResourceManager.GetString("procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string quote {
            get {
                return ResourceManager.GetString("quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Also.
        /// </summary>
        internal static string relatedTopics {
            get {
                return ResourceManager.GetString("relatedTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Also.
        /// </summary>
        internal static string RelatedTopicsTitle {
            get {
                return ResourceManager.GetString("RelatedTopicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        internal static string sampleRef {
            get {
                return ResourceManager.GetString("sampleRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Content.
        /// </summary>
        internal static string sharedContentBlock {
            get {
                return ResourceManager.GetString("sharedContentBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        internal static string subscript {
            get {
                return ResourceManager.GetString("subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string summary {
            get {
                return ResourceManager.GetString("summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        internal static string superscript {
            get {
                return ResourceManager.GetString("superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string table {
            get {
                return ResourceManager.GetString("table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string term {
            get {
                return ResourceManager.GetString("term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        internal static string token {
            get {
                return ResourceManager.GetString("token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        internal static string ui {
            get {
                return ResourceManager.GetString("ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocalized Text.
        /// </summary>
        internal static string unlocalizedText {
            get {
                return ResourceManager.GetString("unlocalizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User input.
        /// </summary>
        internal static string userInput {
            get {
                return ResourceManager.GetString("userInput", resourceCulture);
            }
        }
    }
}
